GOLDEN = [
    # --- Her edattan en az bir örnek (ünsüz-final ev) ---
    {"lemma": "ev", "edat": "için", "bitisik": False, "expected": "evin için"},
    {"lemma": "ev", "edat": "ile", "bitisik": False, "expected": "ev ile"},
    {"lemma": "ev", "edat": "ile", "bitisik": True, "expected": "evle"},
    {"lemma": "ev", "edat": "göre", "bitisik": False, "expected": "eve göre"},
    {"lemma": "ev", "edat": "kadar", "bitisik": False, "expected": "eve kadar"},
    {"lemma": "ev", "edat": "karşı", "bitisik": False, "expected": "eve karşı"},
    {"lemma": "ev", "edat": "rağmen", "bitisik": False, "expected": "eve rağmen"},
    {"lemma": "ev", "edat": "doğru", "bitisik": False, "expected": "eve doğru"},
    {"lemma": "ev", "edat": "dek", "bitisik": False, "expected": "eve dek"},
    {"lemma": "ev", "edat": "değin", "bitisik": False, "expected": "eve değin"},
    {"lemma": "ev", "edat": "üzere", "bitisik": False, "expected": "eve üzere"},
    {"lemma": "ev", "edat": "önce", "bitisik": False, "expected": "evden önce"},
    {"lemma": "ev", "edat": "sonra", "bitisik": False, "expected": "evden sonra"},
    {"lemma": "ev", "edat": "beri", "bitisik": False, "expected": "evden beri"},
    {"lemma": "ev", "edat": "itibaren", "bitisik": False, "expected": "evden itibaren"},
    {"lemma": "ev", "edat": "başka", "bitisik": False, "expected": "evden başka"},
    {"lemma": "ev", "edat": "dolayı", "bitisik": False, "expected": "evden dolayı"},
    {"lemma": "ev", "edat": "ötürü", "bitisik": False, "expected": "evden ötürü"},
    {"lemma": "ev", "edat": "gibi", "bitisik": False, "expected": "ev gibi"},
    {"lemma": "ev", "edat": "aşkın", "bitisik": False, "expected": "evi aşkın"},

    # --- Ünsüz-final: okul (geri ünlü, u) ---
    {"lemma": "okul", "edat": "için", "bitisik": False, "expected": "okulun için"},
    {"lemma": "okul", "edat": "göre", "bitisik": False, "expected": "okula göre"},
    {"lemma": "okul", "edat": "kadar", "bitisik": False, "expected": "okula kadar"},
    {"lemma": "okul", "edat": "önce", "bitisik": False, "expected": "okuldan önce"},
    {"lemma": "okul", "edat": "sonra", "bitisik": False, "expected": "okuldan sonra"},
    {"lemma": "okul", "edat": "gibi", "bitisik": False, "expected": "okul gibi"},
    {"lemma": "okul", "edat": "ile", "bitisik": False, "expected": "okul ile"},
    {"lemma": "okul", "edat": "ile", "bitisik": True, "expected": "okulla"},
    {"lemma": "okul", "edat": "aşkın", "bitisik": False, "expected": "okulu aşkın"},

    # --- Ünsüz-final: kap (geri ünlü, a; p->b yumuşama, abl=kaptan) ---
    {"lemma": "kap", "edat": "için", "bitisik": False, "expected": "kabın için"},
    {"lemma": "kap", "edat": "göre", "bitisik": False, "expected": "kaba göre"},
    {"lemma": "kap", "edat": "önce", "bitisik": False, "expected": "kaptan önce"},
    {"lemma": "kap", "edat": "başka", "bitisik": False, "expected": "kaptan başka"},
    {"lemma": "kap", "edat": "aşkın", "bitisik": False, "expected": "kabı aşkın"},
    {"lemma": "kap", "edat": "gibi", "bitisik": False, "expected": "kap gibi"},

    # --- Ünsüz-final: ağaç (geri ünlü, a; ç->c yumuşama, abl=ağaçtan) ---
    {"lemma": "ağaç", "edat": "için", "bitisik": False, "expected": "ağacın için"},
    {"lemma": "ağaç", "edat": "göre", "bitisik": False, "expected": "ağaca göre"},
    {"lemma": "ağaç", "edat": "kadar", "bitisik": False, "expected": "ağaca kadar"},
    {"lemma": "ağaç", "edat": "önce", "bitisik": False, "expected": "ağaçtan önce"},
    {"lemma": "ağaç", "edat": "beri", "bitisik": False, "expected": "ağaçtan beri"},
    {"lemma": "ağaç", "edat": "aşkın", "bitisik": False, "expected": "ağacı aşkın"},
    {"lemma": "ağaç", "edat": "gibi", "bitisik": False, "expected": "ağaç gibi"},

    # --- Ünlü-final: araba (geri ünlü, a) ---
    {"lemma": "araba", "edat": "için", "bitisik": False, "expected": "arabanın için"},
    {"lemma": "araba", "edat": "göre", "bitisik": False, "expected": "arabaya göre"},
    {"lemma": "araba", "edat": "kadar", "bitisik": False, "expected": "arabaya kadar"},
    {"lemma": "araba", "edat": "doğru", "bitisik": False, "expected": "arabaya doğru"},
    {"lemma": "araba", "edat": "önce", "bitisik": False, "expected": "arabadan önce"},
    {"lemma": "araba", "edat": "sonra", "bitisik": False, "expected": "arabadan sonra"},
    {"lemma": "araba", "edat": "gibi", "bitisik": False, "expected": "araba gibi"},
    {"lemma": "araba", "edat": "ile", "bitisik": False, "expected": "araba ile"},
    {"lemma": "araba", "edat": "ile", "bitisik": True, "expected": "arabayla"},
    {"lemma": "araba", "edat": "aşkın", "bitisik": False, "expected": "arabayı aşkın"},

    # --- köy (ön ünlü ö; y ile biter -> ünsüz-final) ---
    {"lemma": "köy", "edat": "için", "bitisik": False, "expected": "köyün için"},
    {"lemma": "köy", "edat": "göre", "bitisik": False, "expected": "köye göre"},
    {"lemma": "köy", "edat": "önce", "bitisik": False, "expected": "köyden önce"},
    {"lemma": "köy", "edat": "beri", "bitisik": False, "expected": "köyden beri"},
    {"lemma": "köy", "edat": "ile", "bitisik": False, "expected": "köy ile"},
    {"lemma": "köy", "edat": "ile", "bitisik": True, "expected": "köyle"},
    {"lemma": "köy", "edat": "gibi", "bitisik": False, "expected": "köy gibi"},
    {"lemma": "köy", "edat": "aşkın", "bitisik": False, "expected": "köyü aşkın"},

    # --- Zamirler (decline tablosundan) ---
    {"lemma": "ben", "edat": "için", "bitisik": False, "expected": "benim için"},
    {"lemma": "ben", "edat": "göre", "bitisik": False, "expected": "bana göre"},
    {"lemma": "ben", "edat": "ile", "bitisik": False, "expected": "ben ile"},
    {"lemma": "ben", "edat": "gibi", "bitisik": False, "expected": "ben gibi"},
    {"lemma": "sen", "edat": "için", "bitisik": False, "expected": "senin için"},
    {"lemma": "sen", "edat": "göre", "bitisik": False, "expected": "sana göre"},
    {"lemma": "sen", "edat": "önce", "bitisik": False, "expected": "senden önce"},
    {"lemma": "o", "edat": "için", "bitisik": False, "expected": "onun için"},
    {"lemma": "o", "edat": "göre", "bitisik": False, "expected": "ona göre"},
    {"lemma": "o", "edat": "gibi", "bitisik": False, "expected": "o gibi"},
    {"lemma": "biz", "edat": "için", "bitisik": False, "expected": "bizim için"},
    {"lemma": "biz", "edat": "göre", "bitisik": False, "expected": "bize göre"},
    {"lemma": "siz", "edat": "için", "bitisik": False, "expected": "sizin için"},
    {"lemma": "siz", "edat": "kadar", "bitisik": False, "expected": "size kadar"},
    {"lemma": "onlar", "edat": "için", "bitisik": False, "expected": "onların için"},
    {"lemma": "onlar", "edat": "göre", "bitisik": False, "expected": "onlara göre"},
    {"lemma": "bu", "edat": "için", "bitisik": False, "expected": "bunun için"},
    {"lemma": "bu", "edat": "göre", "bitisik": False, "expected": "buna göre"},
    {"lemma": "bu", "edat": "gibi", "bitisik": False, "expected": "bu gibi"},
    {"lemma": "şu", "edat": "için", "bitisik": False, "expected": "şunun için"},
    {"lemma": "şu", "edat": "önce", "bitisik": False, "expected": "şundan önce"},

    # --- n-gövde zamiri: hepsi (gen=hepsinin) ---
    {"lemma": "hepsi", "edat": "için", "bitisik": False, "expected": "hepsinin için"},
]
