# Elle doğrulanmış Türkçe fiil çekimleri — motordan DEĞİL, dilbilgisinden.
#
# ANAHTAR SÖZLEŞMESİ:
#   Olumlu:  '<tense>.<person>'              ör. 'pres.3sg', 'fut.1sg'
#   Olumsuz: '<tense>.neg.<person>'          ör. 'aorist.neg.3sg', 'pres.neg.3sg'
#            (özel kısaltma: 'neg.pres.3sg' = pres.neg.3sg — SPEC örneğiyle uyum;
#             tutarlılık için burada HEP '<tense>.neg.<person>' kullanılır,
#             ayrıca 'neg.pres.3sg' alias'ı da her fiilde verilir.)
#   Yeterlik: 'ability.<tense>.<person>'     ör. 'ability.pres.3sg'
#   Kişisiz:  'conv_arak'                     (ulaç -ArAk)
#
# tense anahtarları (SPEC §1): pres past fut aorist evid cond necess imp
# person: 1sg 2sg 3sg 1pl 2pl 3pl  (imp'te 2sg/2pl)
#
# Beklenen string'ler elle üretildi; her fiil için SPEC §7'nin zorunlu hücreleri.

GOLDEN = {

    # === Grup 1: Düz çok-heceli ünsüz-final ===
    'anlamak': {
        'pres.3sg': 'anlıyor', 'pres.1sg': 'anlıyorum',
        'past.3sg': 'anladı', 'past.1sg': 'anladım',
        'fut.3sg': 'anlayacak', 'fut.1sg': 'anlayacağım',
        'aorist.3sg': 'anlar', 'aorist.neg.3sg': 'anlamaz',
        'evid.3sg': 'anlamış', 'cond.3sg': 'anlasa', 'necess.3sg': 'anlamalı',
        'imp.2sg': 'anla', 'imp.2pl': 'anlayın',
        'conv_arak': 'anlayarak', 'ability.pres.3sg': 'anlayabiliyor',
        'pres.neg.3sg': 'anlamıyor', 'neg.pres.3sg': 'anlamıyor',
    },
    'çalışmak': {
        'pres.3sg': 'çalışıyor', 'pres.1sg': 'çalışıyorum',
        'past.3sg': 'çalıştı', 'past.1sg': 'çalıştım',
        'fut.3sg': 'çalışacak', 'fut.1sg': 'çalışacağım',
        'aorist.3sg': 'çalışır', 'aorist.neg.3sg': 'çalışmaz',
        'evid.3sg': 'çalışmış', 'cond.3sg': 'çalışsa', 'necess.3sg': 'çalışmalı',
        'imp.2sg': 'çalış', 'imp.2pl': 'çalışın',
        'conv_arak': 'çalışarak', 'ability.pres.3sg': 'çalışabiliyor',
        'pres.neg.3sg': 'çalışmıyor', 'neg.pres.3sg': 'çalışmıyor',
    },
    'düşünmek': {
        'pres.3sg': 'düşünüyor', 'pres.1sg': 'düşünüyorum',
        'past.3sg': 'düşündü', 'past.1sg': 'düşündüm',
        'fut.3sg': 'düşünecek', 'fut.1sg': 'düşüneceğim',
        'aorist.3sg': 'düşünür', 'aorist.neg.3sg': 'düşünmez',
        'evid.3sg': 'düşünmüş', 'cond.3sg': 'düşünse', 'necess.3sg': 'düşünmeli',
        'imp.2sg': 'düşün', 'imp.2pl': 'düşünün',
        'conv_arak': 'düşünerek', 'ability.pres.3sg': 'düşünebiliyor',
        'pres.neg.3sg': 'düşünmüyor', 'neg.pres.3sg': 'düşünmüyor',
    },
    'oturmak': {
        'pres.3sg': 'oturuyor', 'pres.1sg': 'oturuyorum',
        'past.3sg': 'oturdu', 'past.1sg': 'oturdum',
        'fut.3sg': 'oturacak', 'fut.1sg': 'oturacağım',
        'aorist.3sg': 'oturur', 'aorist.neg.3sg': 'oturmaz',
        'evid.3sg': 'oturmuş', 'cond.3sg': 'otursa', 'necess.3sg': 'oturmalı',
        'imp.2sg': 'otur', 'imp.2pl': 'oturun',
        'conv_arak': 'oturarak', 'ability.pres.3sg': 'oturabiliyor',
        'pres.neg.3sg': 'oturmuyor', 'neg.pres.3sg': 'oturmuyor',
    },
    'konuşmak': {
        'pres.3sg': 'konuşuyor', 'pres.1sg': 'konuşuyorum',
        'past.3sg': 'konuştu', 'past.1sg': 'konuştum',
        'fut.3sg': 'konuşacak', 'fut.1sg': 'konuşacağım',
        'aorist.3sg': 'konuşur', 'aorist.neg.3sg': 'konuşmaz',
        'evid.3sg': 'konuşmuş', 'cond.3sg': 'konuşsa', 'necess.3sg': 'konuşmalı',
        'imp.2sg': 'konuş', 'imp.2pl': 'konuşun',
        'conv_arak': 'konuşarak', 'ability.pres.3sg': 'konuşabiliyor',
        'pres.neg.3sg': 'konuşmuyor', 'neg.pres.3sg': 'konuşmuyor',
    },

    # === Grup 2: Ünlü-final ===
    'okumak': {
        'pres.3sg': 'okuyor', 'pres.1sg': 'okuyorum',
        'past.3sg': 'okudu', 'past.1sg': 'okudum',
        'fut.3sg': 'okuyacak', 'fut.1sg': 'okuyacağım',
        'aorist.3sg': 'okur', 'aorist.neg.3sg': 'okumaz',
        'evid.3sg': 'okumuş', 'cond.3sg': 'okusa', 'necess.3sg': 'okumalı',
        'imp.2sg': 'oku', 'imp.2pl': 'okuyun',
        'conv_arak': 'okuyarak', 'ability.pres.3sg': 'okuyabiliyor',
        'pres.neg.3sg': 'okumuyor', 'neg.pres.3sg': 'okumuyor',
    },
    'beklemek': {
        'pres.3sg': 'bekliyor', 'pres.1sg': 'bekliyorum',
        'past.3sg': 'bekledi', 'past.1sg': 'bekledim',
        'fut.3sg': 'bekleyecek', 'fut.1sg': 'bekleyeceğim',
        'aorist.3sg': 'bekler', 'aorist.neg.3sg': 'beklemez',
        'evid.3sg': 'beklemiş', 'cond.3sg': 'beklese', 'necess.3sg': 'beklemeli',
        'imp.2sg': 'bekle', 'imp.2pl': 'bekleyin',
        'conv_arak': 'bekleyerek', 'ability.pres.3sg': 'bekleyebiliyor',
        'pres.neg.3sg': 'beklemiyor', 'neg.pres.3sg': 'beklemiyor',
    },
    'başlamak': {
        'pres.3sg': 'başlıyor', 'pres.1sg': 'başlıyorum',
        'past.3sg': 'başladı', 'past.1sg': 'başladım',
        'fut.3sg': 'başlayacak', 'fut.1sg': 'başlayacağım',
        'aorist.3sg': 'başlar', 'aorist.neg.3sg': 'başlamaz',
        'evid.3sg': 'başlamış', 'cond.3sg': 'başlasa', 'necess.3sg': 'başlamalı',
        'imp.2sg': 'başla', 'imp.2pl': 'başlayın',
        'conv_arak': 'başlayarak', 'ability.pres.3sg': 'başlayabiliyor',
        'pres.neg.3sg': 'başlamıyor', 'neg.pres.3sg': 'başlamıyor',
    },
    'yürümek': {
        'pres.3sg': 'yürüyor', 'pres.1sg': 'yürüyorum',
        'past.3sg': 'yürüdü', 'past.1sg': 'yürüdüm',
        'fut.3sg': 'yürüyecek', 'fut.1sg': 'yürüyeceğim',
        'aorist.3sg': 'yürür', 'aorist.neg.3sg': 'yürümez',
        'evid.3sg': 'yürümüş', 'cond.3sg': 'yürüse', 'necess.3sg': 'yürümeli',
        'imp.2sg': 'yürü', 'imp.2pl': 'yürüyün',
        'conv_arak': 'yürüyerek', 'ability.pres.3sg': 'yürüyebiliyor',
        'pres.neg.3sg': 'yürümüyor', 'neg.pres.3sg': 'yürümüyor',
    },
    'aramak': {
        'pres.3sg': 'arıyor', 'pres.1sg': 'arıyorum',
        'past.3sg': 'aradı', 'past.1sg': 'aradım',
        'fut.3sg': 'arayacak', 'fut.1sg': 'arayacağım',
        'aorist.3sg': 'arar', 'aorist.neg.3sg': 'aramaz',
        'evid.3sg': 'aramış', 'cond.3sg': 'arasa', 'necess.3sg': 'aramalı',
        'imp.2sg': 'ara', 'imp.2pl': 'arayın',
        'conv_arak': 'arayarak', 'ability.pres.3sg': 'arayabiliyor',
        'pres.neg.3sg': 'aramıyor', 'neg.pres.3sg': 'aramıyor',
    },

    # === Grup 3: Tek-heceli -Ir aorist (istisna) ===
    'gelmek': {
        'pres.3sg': 'geliyor', 'pres.1sg': 'geliyorum',
        'past.3sg': 'geldi', 'past.1sg': 'geldim',
        'fut.3sg': 'gelecek', 'fut.1sg': 'geleceğim',
        'aorist.3sg': 'gelir', 'aorist.neg.3sg': 'gelmez',
        'aorist.neg.1sg': 'gelmem',
        'evid.3sg': 'gelmiş', 'cond.3sg': 'gelse', 'necess.3sg': 'gelmeli',
        'imp.2sg': 'gel', 'imp.2pl': 'gelin',
        'conv_arak': 'gelerek', 'ability.pres.3sg': 'gelebiliyor',
        'pres.neg.3sg': 'gelmiyor', 'neg.pres.3sg': 'gelmiyor',
    },
    'almak': {
        'pres.3sg': 'alıyor', 'pres.1sg': 'alıyorum',
        'past.3sg': 'aldı', 'past.1sg': 'aldım',
        'fut.3sg': 'alacak', 'fut.1sg': 'alacağım',
        'aorist.3sg': 'alır', 'aorist.neg.3sg': 'almaz',
        'aorist.neg.1sg': 'almam',
        'evid.3sg': 'almış', 'cond.3sg': 'alsa', 'necess.3sg': 'almalı',
        'imp.2sg': 'al', 'imp.2pl': 'alın',
        'conv_arak': 'alarak', 'ability.pres.3sg': 'alabiliyor',
        'pres.neg.3sg': 'almıyor', 'neg.pres.3sg': 'almıyor',
    },
    'olmak': {
        'pres.3sg': 'oluyor', 'pres.1sg': 'oluyorum',
        'past.3sg': 'oldu', 'past.1sg': 'oldum',
        'fut.3sg': 'olacak', 'fut.1sg': 'olacağım',
        'aorist.3sg': 'olur', 'aorist.neg.3sg': 'olmaz',
        'evid.3sg': 'olmuş', 'cond.3sg': 'olsa', 'necess.3sg': 'olmalı',
        'imp.2sg': 'ol', 'imp.2pl': 'olun',
        'conv_arak': 'olarak', 'ability.pres.3sg': 'olabiliyor',
        'pres.neg.3sg': 'olmuyor', 'neg.pres.3sg': 'olmuyor',
    },
    'görmek': {
        'pres.3sg': 'görüyor', 'pres.1sg': 'görüyorum',
        'past.3sg': 'gördü', 'past.1sg': 'gördüm',
        'fut.3sg': 'görecek', 'fut.1sg': 'göreceğim',
        'aorist.3sg': 'görür', 'aorist.neg.3sg': 'görmez',
        'evid.3sg': 'görmüş', 'cond.3sg': 'görse', 'necess.3sg': 'görmeli',
        'imp.2sg': 'gör', 'imp.2pl': 'görün',
        'conv_arak': 'görerek', 'ability.pres.3sg': 'görebiliyor',
        'pres.neg.3sg': 'görmüyor', 'neg.pres.3sg': 'görmüyor',
    },
    'vermek': {
        'pres.3sg': 'veriyor', 'pres.1sg': 'veriyorum',
        'past.3sg': 'verdi', 'past.1sg': 'verdim',
        'fut.3sg': 'verecek', 'fut.1sg': 'vereceğim',
        'aorist.3sg': 'verir', 'aorist.neg.3sg': 'vermez',
        'evid.3sg': 'vermiş', 'cond.3sg': 'verse', 'necess.3sg': 'vermeli',
        'imp.2sg': 'ver', 'imp.2pl': 'verin',
        'conv_arak': 'vererek', 'ability.pres.3sg': 'verebiliyor',
        'pres.neg.3sg': 'vermiyor', 'neg.pres.3sg': 'vermiyor',
    },
    'bilmek': {
        'pres.3sg': 'biliyor', 'pres.1sg': 'biliyorum',
        'past.3sg': 'bildi', 'past.1sg': 'bildim',
        'fut.3sg': 'bilecek', 'fut.1sg': 'bileceğim',
        'aorist.3sg': 'bilir', 'aorist.neg.3sg': 'bilmez',
        'evid.3sg': 'bilmiş', 'cond.3sg': 'bilse', 'necess.3sg': 'bilmeli',
        'imp.2sg': 'bil', 'imp.2pl': 'bilin',
        'conv_arak': 'bilerek', 'ability.pres.3sg': 'bilebiliyor',
        'pres.neg.3sg': 'bilmiyor', 'neg.pres.3sg': 'bilmiyor',
    },
    'durmak': {
        'pres.3sg': 'duruyor', 'pres.1sg': 'duruyorum',
        'past.3sg': 'durdu', 'past.1sg': 'durdum',
        'fut.3sg': 'duracak', 'fut.1sg': 'duracağım',
        'aorist.3sg': 'durur', 'aorist.neg.3sg': 'durmaz',
        'evid.3sg': 'durmuş', 'cond.3sg': 'dursa', 'necess.3sg': 'durmalı',
        'imp.2sg': 'dur', 'imp.2pl': 'durun',
        'conv_arak': 'durarak', 'ability.pres.3sg': 'durabiliyor',
        'pres.neg.3sg': 'durmuyor', 'neg.pres.3sg': 'durmuyor',
    },

    # === Grup 4: Tek-heceli -Ar aorist (düzenli) ===
    'yapmak': {
        'pres.3sg': 'yapıyor', 'pres.1sg': 'yapıyorum',
        'past.3sg': 'yaptı', 'past.1sg': 'yaptım',
        'fut.3sg': 'yapacak', 'fut.1sg': 'yapacağım',
        'aorist.3sg': 'yapar', 'aorist.neg.3sg': 'yapmaz',
        'aorist.neg.1sg': 'yapmam',
        'evid.3sg': 'yapmış', 'cond.3sg': 'yapsa', 'necess.3sg': 'yapmalı',
        'imp.2sg': 'yap', 'imp.2pl': 'yapın',
        'conv_arak': 'yaparak', 'ability.pres.3sg': 'yapabiliyor',
        'pres.neg.3sg': 'yapmıyor', 'neg.pres.3sg': 'yapmıyor',
    },
    'yazmak': {
        'pres.3sg': 'yazıyor', 'pres.1sg': 'yazıyorum',
        'past.3sg': 'yazdı', 'past.1sg': 'yazdım',
        'fut.3sg': 'yazacak', 'fut.1sg': 'yazacağım',
        'aorist.3sg': 'yazar', 'aorist.neg.3sg': 'yazmaz',
        'evid.3sg': 'yazmış', 'cond.3sg': 'yazsa', 'necess.3sg': 'yazmalı',
        'imp.2sg': 'yaz', 'imp.2pl': 'yazın',
        'conv_arak': 'yazarak', 'ability.pres.3sg': 'yazabiliyor',
        'pres.neg.3sg': 'yazmıyor', 'neg.pres.3sg': 'yazmıyor',
    },
    'bakmak': {
        'pres.3sg': 'bakıyor', 'pres.1sg': 'bakıyorum',
        'past.3sg': 'baktı', 'past.1sg': 'baktım',
        'fut.3sg': 'bakacak', 'fut.1sg': 'bakacağım',
        'aorist.3sg': 'bakar', 'aorist.neg.3sg': 'bakmaz',
        'evid.3sg': 'bakmış', 'cond.3sg': 'baksa', 'necess.3sg': 'bakmalı',
        'imp.2sg': 'bak', 'imp.2pl': 'bakın',
        'conv_arak': 'bakarak', 'ability.pres.3sg': 'bakabiliyor',
        'pres.neg.3sg': 'bakmıyor', 'neg.pres.3sg': 'bakmıyor',
    },
    'sarmak': {
        'pres.3sg': 'sarıyor', 'pres.1sg': 'sarıyorum',
        'past.3sg': 'sardı', 'past.1sg': 'sardım',
        'fut.3sg': 'saracak', 'fut.1sg': 'saracağım',
        'aorist.3sg': 'sarar', 'aorist.neg.3sg': 'sarmaz',
        'evid.3sg': 'sarmış', 'cond.3sg': 'sarsa', 'necess.3sg': 'sarmalı',
        'imp.2sg': 'sar', 'imp.2pl': 'sarın',
        'conv_arak': 'sararak', 'ability.pres.3sg': 'sarabiliyor',
        'pres.neg.3sg': 'sarmıyor', 'neg.pres.3sg': 'sarmıyor',
    },
    'gülmek': {
        'pres.3sg': 'gülüyor', 'pres.1sg': 'gülüyorum',
        'past.3sg': 'güldü', 'past.1sg': 'güldüm',
        'fut.3sg': 'gülecek', 'fut.1sg': 'güleceğim',
        'aorist.3sg': 'güler', 'aorist.neg.3sg': 'gülmez',
        'evid.3sg': 'gülmüş', 'cond.3sg': 'gülse', 'necess.3sg': 'gülmeli',
        'imp.2sg': 'gül', 'imp.2pl': 'gülün',
        'conv_arak': 'gülerek', 'ability.pres.3sg': 'gülebiliyor',
        'pres.neg.3sg': 'gülmüyor', 'neg.pres.3sg': 'gülmüyor',
    },

    # === Grup 5: Yumuşama (t→d ünlü önünde; -DI önünde t kalır) ===
    'gitmek': {
        'pres.3sg': 'gidiyor', 'pres.1sg': 'gidiyorum',
        'past.3sg': 'gitti', 'past.1sg': 'gittim',
        'fut.3sg': 'gidecek', 'fut.1sg': 'gideceğim',
        'aorist.3sg': 'gider', 'aorist.neg.3sg': 'gitmez',
        'evid.3sg': 'gitmiş', 'cond.3sg': 'gitse', 'necess.3sg': 'gitmeli',
        'imp.2sg': 'git', 'imp.2pl': 'gidin',
        'conv_arak': 'giderek', 'ability.pres.3sg': 'gidebiliyor',
        'pres.neg.3sg': 'gitmiyor', 'neg.pres.3sg': 'gitmiyor',
    },
    'etmek': {
        'pres.3sg': 'ediyor', 'pres.1sg': 'ediyorum',
        'past.3sg': 'etti', 'past.1sg': 'ettim',
        'fut.3sg': 'edecek', 'fut.1sg': 'edeceğim',
        'aorist.3sg': 'eder', 'aorist.neg.3sg': 'etmez',
        'evid.3sg': 'etmiş', 'cond.3sg': 'etse', 'necess.3sg': 'etmeli',
        'imp.2sg': 'et', 'imp.2pl': 'edin',
        'conv_arak': 'ederek', 'ability.pres.3sg': 'edebiliyor',
        'pres.neg.3sg': 'etmiyor', 'neg.pres.3sg': 'etmiyor',
    },

    # === Grup 6: ye / de özel sınıfı ===
    'yemek': {
        'pres.3sg': 'yiyor', 'pres.1sg': 'yiyorum',
        'past.3sg': 'yedi', 'past.1sg': 'yedim',
        'fut.3sg': 'yiyecek', 'fut.1sg': 'yiyeceğim',
        'aorist.3sg': 'yer', 'aorist.neg.3sg': 'yemez',
        'evid.3sg': 'yemiş', 'cond.3sg': 'yese', 'necess.3sg': 'yemeli',
        'imp.2sg': 'ye', 'imp.2pl': 'yiyin',
        'conv_arak': 'yiyerek', 'ability.pres.3sg': 'yiyebiliyor',
        'pres.neg.3sg': 'yemiyor', 'neg.pres.3sg': 'yemiyor',
    },
    'demek': {
        'pres.3sg': 'diyor', 'pres.1sg': 'diyorum',
        'past.3sg': 'dedi', 'past.1sg': 'dedim',
        'fut.3sg': 'diyecek', 'fut.1sg': 'diyeceğim',
        'aorist.3sg': 'der', 'aorist.neg.3sg': 'demez',
        'evid.3sg': 'demiş', 'cond.3sg': 'dese', 'necess.3sg': 'demeli',
        'imp.2sg': 'de', 'imp.2pl': 'diyin',
        'conv_arak': 'diyerek', 'ability.pres.3sg': 'diyebiliyor',
        'pres.neg.3sg': 'demiyor', 'neg.pres.3sg': 'demiyor',
    },

    # === Grup 7: Yuvarlak-ünlü harmoni (ek örnekler) ===
    'sormak': {
        'pres.3sg': 'soruyor', 'pres.1sg': 'soruyorum',
        'past.3sg': 'sordu', 'past.1sg': 'sordum',
        'fut.3sg': 'soracak', 'fut.1sg': 'soracağım',
        'aorist.3sg': 'sorar', 'aorist.neg.3sg': 'sormaz',
        'evid.3sg': 'sormuş', 'cond.3sg': 'sorsa', 'necess.3sg': 'sormalı',
        'imp.2sg': 'sor', 'imp.2pl': 'sorun',
        'conv_arak': 'sorarak', 'ability.pres.3sg': 'sorabiliyor',
        'pres.neg.3sg': 'sormuyor', 'neg.pres.3sg': 'sormuyor',
    },
    'bulmak': {
        'pres.3sg': 'buluyor', 'pres.1sg': 'buluyorum',
        'past.3sg': 'buldu', 'past.1sg': 'buldum',
        'fut.3sg': 'bulacak', 'fut.1sg': 'bulacağım',
        'aorist.3sg': 'bulur', 'aorist.neg.3sg': 'bulmaz',
        'evid.3sg': 'bulmuş', 'cond.3sg': 'bulsa', 'necess.3sg': 'bulmalı',
        'imp.2sg': 'bul', 'imp.2pl': 'bulun',
        'conv_arak': 'bularak', 'ability.pres.3sg': 'bulabiliyor',
        'pres.neg.3sg': 'bulmuyor', 'neg.pres.3sg': 'bulmuyor',
    },
    'ölmek': {
        'pres.3sg': 'ölüyor', 'pres.1sg': 'ölüyorum',
        'past.3sg': 'öldü', 'past.1sg': 'öldüm',
        'fut.3sg': 'ölecek', 'fut.1sg': 'öleceğim',
        'aorist.3sg': 'ölür', 'aorist.neg.3sg': 'ölmez',
        'evid.3sg': 'ölmüş', 'cond.3sg': 'ölse', 'necess.3sg': 'ölmeli',
        'imp.2sg': 'öl', 'imp.2pl': 'ölün',
        'conv_arak': 'ölerek', 'ability.pres.3sg': 'ölebiliyor',
        'pres.neg.3sg': 'ölmüyor', 'neg.pres.3sg': 'ölmüyor',
    },

    # === Grup 8: Ettirgen / uzun gövde (düzenli olduğu doğrulanır) ===
    'anlatmak': {
        'pres.3sg': 'anlatıyor', 'pres.1sg': 'anlatıyorum',
        'past.3sg': 'anlattı', 'past.1sg': 'anlattım',
        'fut.3sg': 'anlatacak', 'fut.1sg': 'anlatacağım',
        'aorist.3sg': 'anlatır', 'aorist.neg.3sg': 'anlatmaz',
        'evid.3sg': 'anlatmış', 'cond.3sg': 'anlatsa', 'necess.3sg': 'anlatmalı',
        'imp.2sg': 'anlat', 'imp.2pl': 'anlatın',
        'conv_arak': 'anlatarak', 'ability.pres.3sg': 'anlatabiliyor',
        'pres.neg.3sg': 'anlatmıyor', 'neg.pres.3sg': 'anlatmıyor',
    },
    'güldürmek': {
        'pres.3sg': 'güldürüyor', 'pres.1sg': 'güldürüyorum',
        'past.3sg': 'güldürdü', 'past.1sg': 'güldürdüm',
        'fut.3sg': 'güldürecek', 'fut.1sg': 'güldüreceğim',
        'aorist.3sg': 'güldürür', 'aorist.neg.3sg': 'güldürmez',
        'evid.3sg': 'güldürmüş', 'cond.3sg': 'güldürse', 'necess.3sg': 'güldürmeli',
        'imp.2sg': 'güldür', 'imp.2pl': 'güldürün',
        'conv_arak': 'güldürerek', 'ability.pres.3sg': 'güldürebiliyor',
        'pres.neg.3sg': 'güldürmüyor', 'neg.pres.3sg': 'güldürmüyor',
    },
    'temizlemek': {
        'pres.3sg': 'temizliyor', 'pres.1sg': 'temizliyorum',
        'past.3sg': 'temizledi', 'past.1sg': 'temizledim',
        'fut.3sg': 'temizleyecek', 'fut.1sg': 'temizleyeceğim',
        'aorist.3sg': 'temizler', 'aorist.neg.3sg': 'temizlemez',
        'evid.3sg': 'temizlemiş', 'cond.3sg': 'temizlese', 'necess.3sg': 'temizlemeli',
        'imp.2sg': 'temizle', 'imp.2pl': 'temizleyin',
        'conv_arak': 'temizleyerek', 'ability.pres.3sg': 'temizleyebiliyor',
        'pres.neg.3sg': 'temizlemiyor', 'neg.pres.3sg': 'temizlemiyor',
    },

    # === Ek fiiller (kapsam/harmoni çeşitliliği) ===
    'varmak': {
        'pres.3sg': 'varıyor', 'pres.1sg': 'varıyorum',
        'past.3sg': 'vardı', 'past.1sg': 'vardım',
        'fut.3sg': 'varacak', 'fut.1sg': 'varacağım',
        'aorist.3sg': 'varır', 'aorist.neg.3sg': 'varmaz',
        'evid.3sg': 'varmış', 'cond.3sg': 'varsa', 'necess.3sg': 'varmalı',
        'imp.2sg': 'var', 'imp.2pl': 'varın',
        'conv_arak': 'vararak', 'ability.pres.3sg': 'varabiliyor',
        'pres.neg.3sg': 'varmıyor', 'neg.pres.3sg': 'varmıyor',
    },
    'vurmak': {
        'pres.3sg': 'vuruyor', 'pres.1sg': 'vuruyorum',
        'past.3sg': 'vurdu', 'past.1sg': 'vurdum',
        'fut.3sg': 'vuracak', 'fut.1sg': 'vuracağım',
        'aorist.3sg': 'vurur', 'aorist.neg.3sg': 'vurmaz',
        'evid.3sg': 'vurmuş', 'cond.3sg': 'vursa', 'necess.3sg': 'vurmalı',
        'imp.2sg': 'vur', 'imp.2pl': 'vurun',
        'conv_arak': 'vurarak', 'ability.pres.3sg': 'vurabiliyor',
        'pres.neg.3sg': 'vurmuyor', 'neg.pres.3sg': 'vurmuyor',
    },
    'kalmak': {
        'pres.3sg': 'kalıyor', 'pres.1sg': 'kalıyorum',
        'past.3sg': 'kaldı', 'past.1sg': 'kaldım',
        'fut.3sg': 'kalacak', 'fut.1sg': 'kalacağım',
        'aorist.3sg': 'kalır', 'aorist.neg.3sg': 'kalmaz',
        'evid.3sg': 'kalmış', 'cond.3sg': 'kalsa', 'necess.3sg': 'kalmalı',
        'imp.2sg': 'kal', 'imp.2pl': 'kalın',
        'conv_arak': 'kalarak', 'ability.pres.3sg': 'kalabiliyor',
        'pres.neg.3sg': 'kalmıyor', 'neg.pres.3sg': 'kalmıyor',
    },
    'sanmak': {
        'pres.3sg': 'sanıyor', 'pres.1sg': 'sanıyorum',
        'past.3sg': 'sandı', 'past.1sg': 'sandım',
        'fut.3sg': 'sanacak', 'fut.1sg': 'sanacağım',
        'aorist.3sg': 'sanır', 'aorist.neg.3sg': 'sanmaz',
        'evid.3sg': 'sanmış', 'cond.3sg': 'sansa', 'necess.3sg': 'sanmalı',
        'imp.2sg': 'san', 'imp.2pl': 'sanın',
        'conv_arak': 'sanarak', 'ability.pres.3sg': 'sanabiliyor',
        'pres.neg.3sg': 'sanmıyor', 'neg.pres.3sg': 'sanmıyor',
    },
    'gezmek': {
        'pres.3sg': 'geziyor', 'pres.1sg': 'geziyorum',
        'past.3sg': 'gezdi', 'past.1sg': 'gezdim',
        'fut.3sg': 'gezecek', 'fut.1sg': 'gezeceğim',
        'aorist.3sg': 'gezer', 'aorist.neg.3sg': 'gezmez',
        'evid.3sg': 'gezmiş', 'cond.3sg': 'gezse', 'necess.3sg': 'gezmeli',
        'imp.2sg': 'gez', 'imp.2pl': 'gezin',
        'conv_arak': 'gezerek', 'ability.pres.3sg': 'gezebiliyor',
        'pres.neg.3sg': 'gezmiyor', 'neg.pres.3sg': 'gezmiyor',
    },
    'uyumak': {
        'pres.3sg': 'uyuyor', 'pres.1sg': 'uyuyorum',
        'past.3sg': 'uyudu', 'past.1sg': 'uyudum',
        'fut.3sg': 'uyuyacak', 'fut.1sg': 'uyuyacağım',
        'aorist.3sg': 'uyur', 'aorist.neg.3sg': 'uyumaz',
        'evid.3sg': 'uyumuş', 'cond.3sg': 'uyusa', 'necess.3sg': 'uyumalı',
        'imp.2sg': 'uyu', 'imp.2pl': 'uyuyun',
        'conv_arak': 'uyuyarak', 'ability.pres.3sg': 'uyuyabiliyor',
        'pres.neg.3sg': 'uyumuyor', 'neg.pres.3sg': 'uyumuyor',
    },
}
